#! /bin/sh
PATH=$PATH:$HOME/.dotfiles/bspwm/scripts

sxhkd &
polybar myBar &
nm-applet &
emacs --daemon &
numlockx &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color
bspc config active_border_color  \#145f9d
bspc config focused_border_color \#145f9d

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
